#==========================================================#
#----------------------------------------------------------#
#SCRIPT FOR FIG 3 RIGHT PANEL SCRIPT IN KANYAMA ET AL. 2026#
#               WRITTEN BY G. DARGIE, NOV. 2025            #
#----------------------------------------------------------#
#==========================================================#

#======#
#SET UP#
#======#


#SET WORKING DIRECTORY
#NB: USER'S WILL NEED TO SET THEIR OWN WORKING DIRECTORIES


#READ IN DATA (BD=BASE DE DONNÉES)
BD<-read.csv("FieldData-6Sites-Cleaned_12JUNE25.csv", header=TRUE)

names(BD)


#============================================#
#SUBSET THE DATA INTO PLOT AND 250M DATABASES#
#============================================#

#MAKE THE METHOD USED INTO A FACTOR
BD$Method<-as.factor(BD$Method)
levels(BD$Method)


#CREATE 250M DATABASE BY SUBESTTING BY METHOD
DB_250<-BD[which(BD$Method=="Rapid"),]

#CREATE PLOT DATABASE BY SUBSETTING BY METHOD

DB_PLOT<-BD[which(BD$Method=="Full plot"),]


#CHECK IT WORKED

head(DB_PLOT)
head(DB_250)




#==============================#
#REMOVE RAPHIA FROM THE DATASET#
#==============================#

levels(as.factor(DB_PLOT$Species))

DB_PLOT<-DB_PLOT[which(DB_PLOT$Species!="Raphia laurentii De Wild." & DB_PLOT$Species!="Raphia sese De Wild."),]

#CHECK THIS WORKED
levels(as.factor(DB_PLOT$Species))



#================================#
#REMOVE NON-PEAT FROM THE DATASET#
#================================#

levels(as.factor(DB_PLOT$Mapping.Classification..Bart.))

DB_PLOT<-DB_PLOT[which(DB_PLOT$Mapping.Classification..Bart.!="Terra firme"),]

#CHECK THIS WORKED
levels(as.factor(DB_PLOT$Mapping.Classification..Bart.))



#====================================================================#
#GET DATA INTO TRANSECT AND GET MINIMUM STEM NUMBER FOR EACH TRANSECT#
#====================================================================#

#YOU WANT TO COMPARE THE NUMBER OF STEMS FROM THE 6 TRANSECTS

levels(as.factor(DB_PLOT$Transect))

BBK1<-DB_PLOT[which(DB_PLOT$Transect=="BBK1"),]

BLG<-DB_PLOT[which(DB_PLOT$Transect=="BLG"),]

BND1<-DB_PLOT[which(DB_PLOT$Transect=="BND1"),]

IPM<-DB_PLOT[which(DB_PLOT$Transect=="IPM"),]

LBK1<-DB_PLOT[which(DB_PLOT$Transect=="LBK1"),]

MPK1<-DB_PLOT[which(DB_PLOT$Transect=="MPK1"),]


length(BBK1$Species) #358
length(BLG$Species) #225
length(BND1$Species) #44
length(IPM$Species) #238
length(LBK1$Species) #339
length(MPK1$Species) #233





#=========================#
#SAMPLING WITH REPLACEMENT#
#=========================#
#---------#
#---------#
#TRANSECTS#
#---------#
#---------#


#---------------#
#START WITH BBK1#
#---------------#

DF_BBK1_RESAMPLED<-c()									#CREATE EMPTY VECTOR, WHICH AS YOU LOOP THROUGH 1000 TIMES BECOMES A DATAFRAME, AS YOU KEEP APPENDING EACH OF THE 1000 RUNS


for (j in 1:1000){									#START THE 1000 LOOPS
  
  
  RESAMPLED_BBK1_PLOTS <- lapply(1:300, function(size) {			#USE LAPPLY TO RANDOMLY RESAMPLE WITH REPLACEMENT THE SPECIES DATA GOING FROM 1 STEM UP TO 300 STEMS. 300 IS SO THAT WE CAN MAKE A COMPARISON WITH MOST OTHER STUDIES.
    sample(BBK1$Species, size = size, replace = TRUE)			
  })
  
  
  y <- c()											#CREATE AN EMPTY VECTOR y, WHICH WILL CONTAIN THE NUMBER OF SPECIES IN THE 1 TO 300 RANDOMLY RESAMPLED STEMS. SO y HAS A LENGTH OF 300
  
  for (i in 1:300) {									#WE WILL USE A LOOP INSIDE THE LOOP TO RETURN THE NUMBER OF SPECIES IN THE 1 TO 300 RANDOMLY RESAMPLED STEMS
    x<-(length(levels(as.factor(RESAMPLED_BBK1_PLOTS[[i]]))))
    y<-c(y,x)
  }
  
  DF_BBK1_RESAMPLED<-cbind(DF_BBK1_RESAMPLED, y)					#THEN ADD y TO THE "DF_BLACKWATER_RESAMPLED" DATAFRAME WHICH WILL END UP WITH 1000 COLUMNS OF LENGTH 300, AND CONTAINS THE NUMBER OF SPECIES 
  #FROM THE RANDOMLY SAMPLED STEMS. ROW 1 REPRESENT THE RANDOM SAMPLING WHEN THERE IS 1 STEM, 300 REPRESENTS THE RANDOM SAMPLING WITH 300 STEMS
}												#END LOOP




BBK1_LOWER_95CI <- apply(DF_BBK1_RESAMPLED, 1, function(x) sort(x)[25])
BBK1_UPPER_95CI <- apply(DF_BBK1_RESAMPLED, 1, function(x) sort(x)[975])


#---#
#BLG#
#---#

DF_BLG_RESAMPLED<-c()									#CREATE EMPTY VECTOR, WHICH AS YOU LOOP THROUGH 1000 TIMES BECOMES A DATAFRAME, AS YOU KEEP APPENDING EACH OF THE 1000 RUNS


for (j in 1:1000){									#START THE 1000 LOOPS
  
  
  RESAMPLED_BLG_PLOTS <- lapply(1:300, function(size) {				#USE LAPPLY TO RANDOMLY RESAMPLE WITH REPLACEMENT THE SPECIES DATA GOING FROM 1 STEM UP TO 300 STEMS. 300 IS SO THAT WE CAN MAKE A COMPARISON WITH MOST OTHER STUDIES.
    
    sample(BLG$Species, size = size, replace = TRUE)			
  })
  
  
  y <- c()											#CREATE AN EMPTY VECTOR y, WHICH WILL CONTAIN THE NUMBER OF SPECIES IN THE 1 TO 300 RANDOMLY RESAMPLED STEMS. SO y HAS A LENGTH OF 300
  
  for (i in 1:300) {									#WE WILL USE A LOOP INSIDE THE LOOP TO RETURN THE NUMBER OF SPECIES IN THE 1 TO 300 RANDOMLY RESAMPLED STEMS
    x<-(length(levels(as.factor(RESAMPLED_BLG_PLOTS[[i]]))))
    y<-c(y,x)
  }
  
  DF_BLG_RESAMPLED<-cbind(DF_BLG_RESAMPLED, y)					#THEN ADD y TO THE "DF_BLACKWATER_RESAMPLED" DATAFRAME WHICH WILL END UP WITH 100 COLUMNS OF LENGTH 300, AND CONTAINS THE NUMBER OF SPECIES 
  #FROM THE RANDOMLY SAMPLED STEMS. ROW 1 REPRESENT THE RANDOM SAMPLING WHEN THERE IS 1 STEM, 300 REPRESENTS THE RANDOM SAMPLING WITH 300 STEMS
}												#END LOOP




BLG_LOWER_95CI <- apply(DF_BLG_RESAMPLED, 1, function(x) sort(x)[25])
BLG_UPPER_95CI <- apply(DF_BLG_RESAMPLED, 1, function(x) sort(x)[975])




#----#
#BND1#
#----#

DF_BND1_RESAMPLED<-c()									#CREATE EMPTY VECTOR, WHICH AS YOU LOOP THROUGH 1000 TIMES BECOMES A DATAFRAME, AS YOU KEEP APPENDING EACH OF THE 1000 RUNS


for (j in 1:1000){									#START THE 1000 LOOPS
  
  
  RESAMPLED_BND1_PLOTS <- lapply(1:300, function(size) {			#USE LAPPLY TO RANDOMLY RESAMPLE WITH REPLACEMENT THE SPECIES DATA GOING FROM 1 STEM UP TO 300 STEMS. 300 IS SO THAT WE CAN MAKE A COMPARISON WITH MOST OTHER STUDIES.
    sample(BND1$Species, size = size, replace = TRUE)			
  })
  
  
  y <- c()											#CREATE AN EMPTY VECTOR y, WHICH WILL CONTAIN THE NUMBER OF SPECIES IN THE 1 TO 300 RANDOMLY RESAMPLED STEMS. SO y HAS A LENGTH OF 300
  
  for (i in 1:300) {									#WE WILL USE A LOOP INSIDE THE LOOP TO RETURN THE NUMBER OF SPECIES IN THE 1 TO 300 RANDOMLY RESAMPLED STEMS
    x<-(length(levels(as.factor(RESAMPLED_BND1_PLOTS[[i]]))))
    y<-c(y,x)
  }
  
  DF_BND1_RESAMPLED<-cbind(DF_BND1_RESAMPLED, y)					#THEN ADD y TO THE "DF_BLACKWATER_RESAMPLED" DATAFRAME WHICH WILL END UP WITH 1000 COLUMNS OF LENGTH 300, AND CONTAINS THE NUMBER OF SPECIES 
  #FROM THE RANDOMLY SAMPLED STEMS. ROW 1 REPRESENT THE RANDOM SAMPLING WHEN THERE IS 1 STEM, 300 REPRESENTS THE RANDOM SAMPLING WITH 300 STEMS
}												#END LOOP




BND1_LOWER_95CI <- apply(DF_BND1_RESAMPLED, 1, function(x) sort(x)[25])
BND1_UPPER_95CI <- apply(DF_BND1_RESAMPLED, 1, function(x) sort(x)[975])




#---#
#IPM#
#---#

DF_IPM_RESAMPLED<-c()									#CREATE EMPTY VECTOR, WHICH AS YOU LOOP THROUGH 1000 TIMES BECOMES A DATAFRAME, AS YOU KEEP APPENDING EACH OF THE 1000 RUNS


for (j in 1:1000){									#START THE 1000 LOOPS
  
  
  RESAMPLED_IPM_PLOTS <- lapply(1:300, function(size) {				#USE LAPPLY TO RANDOMLY RESAMPLE WITH REPLACEMENT THE SPECIES DATA GOING FROM 1 STEM UP TO 300 STEMS. 300 IS SO THAT WE CAN MAKE A COMPARISON WITH MOST OTHER STUDIES.
    sample(IPM$Species, size = size, replace = TRUE)			
  })
  
  
  y <- c()											#CREATE AN EMPTY VECTOR y, WHICH WILL CONTAIN THE NUMBER OF SPECIES IN THE 1 TO 300 RANDOMLY RESAMPLED STEMS. SO y HAS A LENGTH OF 300
  
  for (i in 1:300) {									#WE WILL USE A LOOP INSIDE THE LOOP TO RETURN THE NUMBER OF SPECIES IN THE 1 TO 300 RANDOMLY RESAMPLED STEMS
    x<-(length(levels(as.factor(RESAMPLED_IPM_PLOTS[[i]]))))
    y<-c(y,x)
  }
  
  DF_IPM_RESAMPLED<-cbind(DF_IPM_RESAMPLED, y)					#THEN ADD y TO THE "DF_BLACKWATER_RESAMPLED" DATAFRAME WHICH WILL END UP WITH 1000 COLUMNS OF LENGTH 300, AND CONTAINS THE NUMBER OF SPECIES 
  #FROM THE RANDOMLY SAMPLED STEMS. ROW 1 REPRESENT THE RANDOM SAMPLING WHEN THERE IS 1 STEM, 300 REPRESENTS THE RANDOM SAMPLING WITH 300 STEMS
}												#END LOOP




IPM_LOWER_95CI <- apply(DF_IPM_RESAMPLED, 1, function(x) sort(x)[25])
IPM_UPPER_95CI <- apply(DF_IPM_RESAMPLED, 1, function(x) sort(x)[975])



#----#
#LBK1#
#----#

DF_LBK1_RESAMPLED<-c()									#CREATE EMPTY VECTOR, WHICH AS YOU LOOP THROUGH 1000 TIMES BECOMES A DATAFRAME, AS YOU KEEP APPENDING EACH OF THE 1000 RUNS


for (j in 1:1000){									#START THE 1000 LOOPS
  
  
  RESAMPLED_LBK1_PLOTS <- lapply(1:300, function(size) {			#USE LAPPLY TO RANDOMLY RESAMPLE WITH REPLACEMENT THE SPECIES DATA GOING FROM 1 STEM UP TO 300 STEMS. 300 IS SO THAT WE CAN MAKE A COMPARISON WITH MOST OTHER STUDIES.
    sample(LBK1$Species, size = size, replace = TRUE)			
  })
  
  
  y <- c()											#CREATE AN EMPTY VECTOR y, WHICH WILL CONTAIN THE NUMBER OF SPECIES IN THE 1 TO 300 RANDOMLY RESAMPLED STEMS. SO y HAS A LENGTH OF 300
  
  for (i in 1:300) {									#WE WILL USE A LOOP INSIDE THE LOOP TO RETURN THE NUMBER OF SPECIES IN THE 1 TO 300 RANDOMLY RESAMPLED STEMS
    x<-(length(levels(as.factor(RESAMPLED_LBK1_PLOTS[[i]]))))
    y<-c(y,x)
  }
  
  DF_LBK1_RESAMPLED<-cbind(DF_LBK1_RESAMPLED, y)					#THEN ADD y TO THE "DF_BLACKWATER_RESAMPLED" DATAFRAME WHICH WILL END UP WITH 1000 COLUMNS OF LENGTH 300, AND CONTAINS THE NUMBER OF SPECIES 
  #FROM THE RANDOMLY SAMPLED STEMS. ROW 1 REPRESENT THE RANDOM SAMPLING WHEN THERE IS 1 STEM, 300 REPRESENTS THE RANDOM SAMPLING WITH 300 STEMS
}												#END LOOP




LBK1_LOWER_95CI <- apply(DF_LBK1_RESAMPLED, 1, function(x) sort(x)[25])
LBK1_UPPER_95CI <- apply(DF_LBK1_RESAMPLED, 1, function(x) sort(x)[975])





#----#
#MPK1#
#----#

DF_MPK1_RESAMPLED<-c()									#CREATE EMPTY VECTOR, WHICH AS YOU LOOP THROUGH 1000 TIMES BECOMES A DATAFRAME, AS YOU KEEP APPENDING EACH OF THE 1000 RUNS


for (j in 1:1000){									#START THE 1000 LOOPS
  
  
  RESAMPLED_MPK1_PLOTS <- lapply(1:300, function(size) {			#USE LAPPLY TO RANDOMLY RESAMPLE WITH REPLACEMENT THE SPECIES DATA GOING FROM 1 STEM UP TO 300 STEMS. 300 IS SO THAT WE CAN MAKE A COMPARISON WITH MOST OTHER STUDIES.
    sample(MPK1$Species, size = size, replace = TRUE)			
  })
  
  
  y <- c()											#CREATE AN EMPTY VECTOR y, WHICH WILL CONTAIN THE NUMBER OF SPECIES IN THE 1 TO 300 RANDOMLY RESAMPLED STEMS. SO y HAS A LENGTH OF 300
  
  for (i in 1:300) {									#WE WILL USE A LOOP INSIDE THE LOOP TO RETURN THE NUMBER OF SPECIES IN THE 1 TO 300 RANDOMLY RESAMPLED STEMS
    x<-(length(levels(as.factor(RESAMPLED_MPK1_PLOTS[[i]]))))
    y<-c(y,x)
  }
  
  DF_MPK1_RESAMPLED<-cbind(DF_MPK1_RESAMPLED, y)					#THEN ADD y TO THE "DF_BLACKWATER_RESAMPLED" DATAFRAME WHICH WILL END UP WITH 1000 COLUMNS OF LENGTH 300, AND CONTAINS THE NUMBER OF SPECIES 
  #FROM THE RANDOMLY SAMPLED STEMS. ROW 1 REPRESENT THE RANDOM SAMPLING WHEN THERE IS 1 STEM, 300 REPRESENTS THE RANDOM SAMPLING WITH 300 STEMS
}												#END LOOP




MPK1_LOWER_95CI <- apply(DF_MPK1_RESAMPLED, 1, function(x) sort(x)[25])
MPK1_UPPER_95CI <- apply(DF_MPK1_RESAMPLED, 1, function(x) sort(x)[975])



#NOW YOU NEED TO GET THE MEAN NUMBER OF SPECIES PER STEM NUMBER FOR EACH DATAFRAME

BBK1_RESAMPLED_MEAN_NO_SPECIES<-rowMeans(DF_BBK1_RESAMPLED)
BLG_RESAMPLED_MEAN_NO_SPECIES<-rowMeans(DF_BLG_RESAMPLED)
BND1_RESAMPLED_MEAN_NO_SPECIES<-rowMeans(DF_BND1_RESAMPLED)
IPM_RESAMPLED_MEAN_NO_SPECIES<-rowMeans(DF_IPM_RESAMPLED)
LBK1_RESAMPLED_MEAN_NO_SPECIES<-rowMeans(DF_LBK1_RESAMPLED)
MPK1_RESAMPLED_MEAN_NO_SPECIES<-rowMeans(DF_MPK1_RESAMPLED)

head(BBK1_RESAMPLED_MEAN_NO_SPECIES)

#-------------#
#OVERALL MEANS#
#-------------#

#GETTING THE MEAN OF MEANS
X<-rbind(BBK1_RESAMPLED_MEAN_NO_SPECIES,BLG_RESAMPLED_MEAN_NO_SPECIES,BND1_RESAMPLED_MEAN_NO_SPECIES,IPM_RESAMPLED_MEAN_NO_SPECIES,LBK1_RESAMPLED_MEAN_NO_SPECIES,MPK1_RESAMPLED_MEAN_NO_SPECIES)
head(X)


MEANOFMEANS<-colMeans(X)
head(MEANOFMEANS)


round(MEANOFMEANS)

#COMBINING ALL DATASETS AND THEN CALCULATING THE MEANS

Y<-cbind(DF_BBK1_RESAMPLED,DF_BLG_RESAMPLED,DF_BND1_RESAMPLED,DF_IPM_RESAMPLED,DF_LBK1_RESAMPLED,DF_MPK1_RESAMPLED)
head(Y)
ncol(Y)


MEANOFCOMBINEDDFS<-rowMeans(Y)
head(MEANOFCOMBINEDDFS)



#--------------------#
#CONFIDENCE INTERVALS#
#--------------------#

COMBINEDDF_LOWER_95CI <- apply(Y, 1, function(x) sort(x)[150])
COMBINEDDF_UPPER_95CI <- apply(Y, 1, function(x) sort(x)[5850])

#NOW 1.96 STANDARD DEVIATION OF MEAN OF MEANS
SD_X<-apply(X, 2, sd)

CI_X<-(1.96*SD_X)/2

UPPER_CI<-MEANOFMEANS+CI_X
LOWER_CI<-MEANOFMEANS-CI_X



#------------------------#
#FIGURE 3 LEFT PANEL PLOT#
#------------------------#

par(mar=c(6,6,1,3))

plot(x = 1,                 
     xlab = "", 
     ylab = "",
     xlim=c(0,300), 
     ylim=c(0,50),
     yaxt="n",
     xaxt="n",
     frame.plot=F,
     type = "n")


STEM<-c(1:300)
polygon(c(STEM, rev(STEM)), c(UPPER_CI, rev(LOWER_CI)), col = rgb(128/255, 128/255, 128/255, 0.2), border = NA)  


par(new=TRUE)
plot(MEANOFMEANS, typ="l", col=rgb(0, 0, 0), xlab="",ylab="", xlim=c(0,300), ylim=c(0,50), lwd=2,cex.lab=2.5, cex.axis=1.5)
mtext("Number of Stems", side=1, line=4, cex=2.5)
mtext("Number of Species", side=2, line=4, cex=2.5)


legend(100,10, legend = c("Transect mean", "Transect 95th CI"), 
       col = c(rgb(0, 0, 0), rgb(128/255, 128/255, 128/255, 0.2))
       , lty = c(1,1), lwd= c(2,4), cex=1.5, bty="n")
